CREATE TABLE IF NOT EXISTS push_tokens (
  token      VARCHAR(255) NOT NULL PRIMARY KEY,
  `lines`    JSON         NOT NULL,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
